version: '2.1'

services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
    - "8080:9000"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - certs:/srv/lantern/certs

  proxy:
    build:
      context: .
      dockerfile: ./proxy/Dockerfile
    ports:
    - "8081:9000"
#    command: 'lantern_generator' # lantern_proxy default
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - certs:/srv/lantern/certs

  database:
    image: healthcheck/postgres
    environment:
      POSTGRES_DB: lantern
      POSTGRES_PASSWORD: lantern-password
      POSTGRES_USER: lantern
    volumes:
#      - db:/var/lib/postgresql/data
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  admin-database:
    image: adminer
    ports:
    - "5050:8080"
    depends_on:
      database:
        condition: service_healthy

volumes:
  certs:
    driver: local